const bairrosESetores = {
    // Zona Norte
    "afranio paiva": "Zona Norte",
    "alto das merces": "Zona Norte",
    "alto do cruzeiro": "Zona Norte",
    "alto dos bandeirantes": "Zona Norte",
    "alvorada": "Zona Norte",
    "arnaldos": "Zona Norte",
    "bairro industrial": "Zona Norte",
    "bairro novo": "Zona Norte",
    "bela vista": "Zona Norte",
    "bom jardim": "Zona Norte",
    "vieiras": "Zona Norte",
    "cabo divino": "Zona Norte",
    "campo eliseos": "Zona Norte",
    "campos sales": "Zona Norte",
    "centenario": "Zona Norte",
    "coroado de cima": "Zona Norte",
    "cruzeiro": "Zona Norte",
    "jardim aeroporto": "Zona Norte",
    "jardim alvorada": "Zona Norte",
    "jardim america": "Zona Norte",
    "jardim beira rio": "Zona Norte",
    "jardim brasil": "Zona Norte",
    "jardim brasil vilela": "Zona Norte",
    "jardim california": "Zona Norte",
    "jardim das acacias": "Zona Norte",
    "jardim dona marieta": "Zona Norte",
    "jardim dos ipes": "Zona Norte",
    "jardim europa": "Zona Norte",
    "jardim italia": "Zona Norte",
    "jardim marieta 2": "Zona Norte",
    "jardim nova esperanca": "Zona Norte",
    "jardim ouro verde": "Zona Norte",
    "jardim panorama": "Zona Norte",
    "jardim primavera": "Zona Norte",
    "jardim santa helena": "Zona Norte",
    "jardim santa maria": "Zona Norte",
    "louviral martins de melo": "Zona Norte",
    "monte libano": "Zona Norte",

    // Zona Sul
    "morada do sol": "Zona Sul",
    "nossa senhora das gracas": "Zona Sul",
    "novo bandeirantes": "Zona Sul",
    "novo horizonte": "Zona Sul",
    "ocia": "Zona Sul",
    "parque de exposicao": "Zona Sul",
    "passa tempo": "Zona Sul",
    "patricios": "Zona Sul",
    "planalto": "Zona Sul",
    "por do sol": "Zona Sul",
    "primavera": "Zona Sul",
    "quatis": "Zona Sul",
    "quinta da boa vista": "Zona Sul",
    "recanto das pedras": "Zona Sul",
    "residencial alto do campestre": "Zona Sul",
    "residencial bem viver": "Zona Sul",
    "residencial cidade jardim": "Zona Sul",
    "residencial cristiano pereira": "Zona Sul",
    "residencial ecoville": "Zona Sul",
    "residencial florenca": "Zona Sul",
    "residencial jardim brasil vilela ii": "Zona Sul",
    "residencial jardim dona marieta": "Zona Sul",
    "residencial jardim ouro verde": "Zona Sul",
    "residencial mirante do lago": "Zona Sul",
    "residencial monte belo": "Zona Sul",
    "residencial santo antonio": "Zona Sul",
    "residencial vila sonho": "Zona Sul",
    "rio bonito (pirabeiraba)": "Zona Sul",
    "romano": "Zona Sul",
    "santa maria": "Zona Sul",
    "sao benedito": "Zona Sul",
    "sao francisco": "Zona Sul",
    "sao jorge": "Zona Sul",
    "sao judas tadeu": "Zona Sul",
    "sao luiz": "Zona Sul",

    // Zona Leste
    "sevilha": "Zona Leste",
    "sinara": "Zona Leste",
    "sobradinho": "Zona Leste",
    "toscano de brito": "Zona Leste",
    "triangulo": "Zona Leste",
    "turmalinas": "Zona Leste",
    "urbano": "Zona Leste",
    "uruguai": "Zona Leste",
    "vale do sol": "Zona Leste",
    "varginha": "Zona Leste",
    "vila amauri": "Zona Leste",
    "vila arandutaba": "Zona Leste",
    "vila augusta": "Zona Leste",
    "vila augusto ribeiro": "Zona Leste",
    "vila bandeirantes": "Zona Leste",
    "vila bela vista": "Zona Leste",
    "vila berenice": "Zona Leste",
    "vila braganca": "Zona Leste",
    "vila brasil": "Zona Leste",
    "vila constantino": "Zona Leste",
    "vila diniz": "Zona Leste",
    "vila escolastica": "Zona Leste",
    "vila fernando de paula marandola": "Zona Leste",
    "vila guarani": "Zona Leste",
    "vila guimaraes": "Zona Leste",
    "vila isabel": "Zona Leste",
    "vila jose fernandes moreira": "Zona Leste",
    "vila jose garcia": "Zona Leste",
    "vila matilde": "Zona Leste",
    "vila nossa senhora das gracas": "Zona Leste",
    "vila nossa senhora de fatima": "Zona Leste",
    "vila nova": "Zona Leste",
    "vila planalto": "Zona Leste",
    "vila por do sol": "Zona Leste",
    "vila romana": "Zona Leste",
    "vila saldanha": "Zona Leste",
    "vila sansao": "Zona Leste",
    "vila sao joao": "Zona Leste",
    "vila sao jorge": "Zona Leste",
    "vila sao sebastiao": "Zona Leste",
    "vila senhor bom jesus": "Zona Leste",
    "vila vicentina": "Zona Leste",
    "feira": "Zona Leste",
    "centro": "Zona Leste"
};
